config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
 
  resources :articles do 
	member do
        	get 'assign_student'
        end
  end
  resources :articlestuds#plural
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :articlestud, optional: true

  validates :title, presence: true,
                    length: { minimum: 5 }
  validates_uniqueness_of :articlestud_id, allow_nil: true

 def self.show_full_list
  Articlestud.all.collect{|p| [p.title, p.id]}
 end
  def remaining_days
  if !return_date.nil?
   days_left=return_date-Date.today
   days_left.to_i
 end
 end
end

app/models/articlestud.rb
class Articlestud < ApplicationRecord
  has_one :article
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
t=Time.now
  end
 
  def show
    @article = Article.find(params[:id])
  end
 
  def new
    @article = Article.new
   
  end
 
  def edit
    @article = Article.find(params[:id])
  end
 
  def create
    @article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
 
  def assign_student
    @article = Article.find(params[:id])
    @article.articlestud_id = params[:article][:articlestud_id]
   if params[:article][:articlestud_id].present?
   @article.borrow_date=Time.now
   @article.return_date=Time.now+864000
   else
     @article.borrow_date=nil
   @article.return_date=nil
   end
   if @article.save
      flash[:notice]  = "successfully updated"
   else
      flash[:error] = "Error: #{@article.errors.messages}"
   end
    redirect_to articles_path
  
 end
def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
   private
    def article_params
      params.require(:article).permit(:title, :text, :discp, :articlestud_id)
    end
end

app/controllers/articlestuds_controller.rb
class ArticlestudsController < ApplicationController
  def index
    @articlestuds = Articlestud.all
  end
 
  def show
    @articlestud = Articlestud.find(params[:id])
  end
 
  def new
    @articlestud = Articlestud.new
  end
 
  def edit
    @articlestud = Articlestud.find(params[:id])
  end
 
  def create
    @articlestud = Articlestud.new(articlestud_params)
 
    if @articlestud.save
      redirect_to @articlestud
    else
      render 'new'
    end
  end
 
  def update
    @articlestud = Articlestud.find(params[:id])
 
    if @articlestud.update(articlestud_params)
      redirect_to @articlestud
    else
      render 'edit'
    end
  end
   private
    def articlestud_params
      params.require(:articlestud).permit(:title, :text, :discp)
    end
end

app/controllers/librarys_controller.rb
class LibrarysController < ApplicationController

def new
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/articlestuds_helper.rb
module ArticlestudsHelper
end

app/helpers/librarys_helper.rb
module LibrarysHelper
end

app/helpers/sree_helper.rb
module SreeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb

<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <center>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :author %><br>
    <%= form.text_area :text %>
  </p>
 <p>
    <%= form.label :description %><br>
    <%= form.text_area :discp %>
  </p>

  <p>
    <%= form.submit :update %>
  </p>
 </center>
<% end %>

app/views/articles/edit.html.erb
<center><h1>Edit details</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>
</center>
 

app/views/articles/index.html.erb
<center><h1>List of books</h1>
<br>

<br>
<table border=1>
  <tr>
    <th>BOOK NAME</th>
    <th>AUTHOR</th>
    <th>DESCRIPTION</th>
   <th>BORROWED BY</th>
 <th>select student name</th>
<th>click to assign</th>
   <th>BORROWED ON</th>
   <th>RETURN DATE</th>
<th>DAYS LEFT</th>
    <th colspan="20"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= truncate(article.discp, :length => 20)%></td>

      <td>&nbsp<t> </t><%= link_to article.articlestud.title, articlestud_path(article.articlestud) if article.articlestud %></td>
      	<%= form_tag(assign_student_article_path(article), method: "get") do %>
		<td><%= select("article", "articlestud_id", Article.show_full_list,{ include_blank: true })%>
      		<td>&nbsp<t> </t><%= submit_tag('Assign')%></td>
    <td><%= article.borrow_date %></td>
    <td><%= article.return_date %></td>

  <td><%= article.remaining_days %></td>
    <td>&nbsp<t> </t><%= link_to 'Edit', edit_article_path(article) %></td>
    <td>&nbsp<t> </t><%= link_to 'Show', article_path(article) %></td>
        <% end %>
      
    </tr>
  <% end %>
</table>
<br>
<%= link_to 'New book', new_article_path %>
<br>
<br>
<td><%= link_to 'Home', welcome_index_path %></td>
</center>

app/views/articles/new.html.erb
<center><h1>New book</h1>
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>
</center>
 

app/views/articles/show.html.erb
<p>
  <strong>book name:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>author name:</strong>
  <%= @article.text %>
</p>
<p>
  <strong>description:</strong>
  <%= @article.discp %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/articlestuds/_form.html.erb

<%= form_with model: @articlestud, local: true do |form| %>
 <% if @articlestud.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@articlestud.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @articlestud.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :section %><br>
    <%= form.text_field :text %>
  </p>
 <p>
    <%= form.label :address %><br>
    <%= form.text_area :discp %>
  </p>
  <p>
    <%= form.submit :update %>
  </p>
 
<% end %>

app/views/articlestuds/edit.html.erb
<h1>Edit details</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articlestuds_path %>

app/views/articlestuds/index.html.erb
<center><h1>List of Students</h1>
<br>
<table border=1>
  <tr>
    <th>NAME</th>
    <th>SECTION</th>

    <th>ADDRESS</th>
    <th>BOOK BORROWED </th>
    <th colspan="10"></th>
  </tr>
 <br>
  <% @articlestuds.each do |articlestud| %>
    <tr>
      <td><%= articlestud.title%></td>
      <td><%= articlestud.text %></td>
      <td><%= truncate(articlestud.discp, :length => 10)%>
      <td>
        <% if articlestud.article %>
	  <%= link_to articlestud.article.title, article_path(articlestud.article) %> 
        <% end %>
      </td>
</td>
      <td>&nbsp<t> </t><%= link_to 'Show', articlestud_path(articlestud) %></td>
      <td>&nbsp<t> </t><%= link_to 'Edit', edit_articlestud_path(articlestud) %></td>
     
    </tr>
  <% end %>
</table>
<br>
<br><%= link_to 'New Student', new_articlestud_path %>
<br>
<br>
<br>
<td><%= link_to 'Home', welcome_index_path %></td></center>

app/views/articlestuds/new.html.erb
<h1>New Student</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articlestuds_path %>

app/views/articlestuds/show.html.erb
<p>
  <strong>name:</strong>
  <%= @articlestud.title%>
</p>
 
<p>
  <strong>section:</strong>
  <%= @articlestud.text %>
</p>
<p>
  <strong>address:</strong>
  <%= @articlestud.discp %>
</p>

<%= link_to 'Edit', edit_articlestud_path(@articlestud) %> |
<%= link_to 'Back', articlestuds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library management app</title>
    
<%= csrf_meta_tags %>

  
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


 </head>

 
 <body>

 <%=link_to "BOOKS", articles_path %>
 <%=link_to "STUDENT", articlestuds_path %>
<% flash.each do |name, msg| %> 
<%=content_tag :div, msg, class: "alert alert-info" %> <% end %>
 <%= yield %>
 

 </body>
 </html>

  

app/views/librarys/new.html.erb
<h1>New Student</h1>
 
<%= form_with scope: :article, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb

<center>
<br>
<br>

<h1>........WELCOME......</h1>
<h2><i>Perfect Partner in Library Management.</i></h2>
</center>
<title>
library app
</title>
<center>
<br>
<br>
<h1><%= link_to 'Books', controller: 'articles' %><h1><t>  </t>
<h1><%= link_to 'Student', controller: 'articlestuds' %></h1>
 <body background="C:\Sites\blog\app\views\welcome\image.jpg">
</body></center>